### ISSUE TITLE
爬虫登录成功判断

### ISSUE THREAD

**Issue by gxb3071393901** [essayZW/BUCTWXServices#10]
学长你好，因为我一直使用你和你的团队开发的轻触BUCT，然后在使用过程中，经常性提示登录失败，密码错误等等。个人感觉是爬虫方面出了问题。

然后在github上发现了咋们的源码。然后我研究了下。感觉有可能是**jwrobot**下的**robot.py**下的登录地方出现了问题。

如下图：![image-20220316154732919](https://gitee.com/gao_x/pic/raw/master/blogImg/2022-03/1647417408784_e596c319-0aba-4ef1-b2aa-51313708f7aa.png)

教务管理系统登录成功后有这么个尾缀。

按照学长的判断方式：

```python
if rep.url == self.baseUrl + '/jwglxt/xtgl/index_initMenu.html':
```

判等情况下因为有尾缀，会不成功。

建议改成如下判断：

```python
if str(rep.url).startswith(self.baseUrl + '/jwglxt/xtgl/index_initMenu.html'):
```

以上是个人的看法，希望对你有帮助。

**Comment by essayZW** [comment]
你说的有道理，我改改

**Comment by essayZW** [comment]
已修改并同步至服务器,感谢
